arquivo:
  diretorio-upload: /app/storage
server:
  port: 8083
  error:
    include-stacktrace: never
spring:
  application.name: sgu-editais-service
  web:
    locale-resolver: fixed
    locale: pt_BR
  devtools:
    livereload:
      enabled: true
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 20MB
  datasource:
    url: jdbc:postgresql://localhost:5432/editais
    username: postgres
    password: 55555


  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: ${keycloak.auth-server-url}/realms/${keycloak.realm}
            user-name-attribute: preferred_username
      resourceserver:
        jwt:
          jwk-set-uri: ${spring.security.oauth2.client.provider.keycloak.issuer-uri}/protocol/openid-connect/certs
  cloud:
    openfeign:
      client:
        config:
          default:
            connect-timeout: 5000
            read-timeout: 20000

authClient:
  base-url: http://gateway:8080/auth
#  client-id: editais-application


resilience4j:
  circuitbreaker:
    instances:
      authServiceClient:
        registerHealthIndicator: true
        slidingWindowSize: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 5s

springdoc:
  api-docs:
    path: /api-doc/docs
  swagger-ui:
    path: /api-doc/swagger.html

keycloak:
  auth-server-url: http://localhost:9090/
  realm: sgu-ufape

common:
  front: http://localhost:3000/


logging:
  level:
    org:
      springframework: DEBUG
---
spring:
  config:
    activate:
      on-profile: docker
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  datasource:
    url: jdbc:postgresql://sgu-editais-db:5432/editais
    username: postgres
    password: password
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${keycloak.auth-server-url}realms/${keycloak.realm}/protocol/openid-connect/certs
keycloak:
  auth-server-url: http://keycloak:8080/
  realm: sgu-ufape


eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery:8761/eureka/
    registerWithEureka: true
    fetchRegistry: true
  instance:
    hostname: sgu-editais-service
    prefer-ip-address: false
